### ISSUE TITLE
Implement a consistent logic for commments

### ISSUE THREAD

**Issue by cmenke42** [mdabir1203/WebserV#10]
https://github.com/mdabir1203/WebserV/blob/aefc9b9602dbb1aad1c7fee21e563ae3e18e6225/webserv/src/config_files/default.conf#L14C14-L14C14

Commetns are not allowed.

root: / #sdlfkgjlkdfgj dsfgdfg sdfg sg 

-> should give an error, since you cant specify multiple root paths

**Comment by AndersLazis** [comment]
Done

**Comment by AndersLazis** [comment]
Finished
