### ISSUE TITLE
Throw error if root or location starts with "."

### ISSUE THREAD

**Issue by cmenke42** [mdabir1203/WebserV#7]
https://github.com/mdabir1203/WebserV/blob/aefc9b9602dbb1aad1c7fee21e563ae3e18e6225/webserv/src/config_files/default.conf#L12C1-L14C13

![283255219-fc9685ac-434a-40dc-8b56-d21e6ed4c42e](https://github.com/mdabir1203/WebserV/assets/122057895/94dec205-d284-4bb2-893e-f92423ca9bdb)

Throw Bad Practice Errror.
-> security vulnerabilty

location ./

or
location
{
root: ./
}

**Comment by AndersLazis** [comment]
done
